# docker-compose.yml
services:
  signal-api:
    image: bbernhard/signal-cli-rest-api
    environment:
      - MODE=json-rpc
    volumes:
      - ./signal-data:/home/.local/share/signal-cli

  bot:
    build: .
    volumes:
      - ./bot-data:/data
    environment:
      - SIGNAL_API=signal-api:8080
      - SIGNAL_PHONE_NUMBER=+49XXXXXXXXXX
      - DATABASE_PATH=/data/test.db
    depends_on:
      - signal-api
    restart: unless-stopped

